name: Trigger auto deployment for cod-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cod-api-AutoDeployTrigger-d25d59ca-ebdf-47f8-b699-753b13d7daa8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CODAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CODAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CODAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: fieldmaps.azurecr.io
          registryUsername: ${{ secrets.CODAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CODAPI_REGISTRY_PASSWORD }}
          containerAppName: cod-api
          resourceGroup: DefaultResourceGroup-WEU
          imageToBuild: fieldmaps.azurecr.io/cod-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


